'use client';

import { useEffect, useRef, useState } from 'react';
import Link from 'next/link';
import { AnimatePresence, MotionConfig, motion, useReducedMotion } from 'framer-motion';
import { Activity, ArrowLeft, ArrowRight, ArrowUpRight, AudioLines, Check, ChevronRight, Clock3, Compass, Flag, HelpCircle, KeyRound, LayoutGrid, Play, RotateCcw, Send, Settings2, ShieldCheck, SlidersHorizontal, Sparkles, Target, TrendingUp, Trophy, Zap } from 'lucide-react';
import { choices, Choice, Config, defaults, Domain, evaluateText, outcome, scenarios, stages, tension, tensionState, threshold } from '@/lib/engine';
import { Session, useArena } from '@/lib/store';
import { Arrival, Atmosphere, Modal, TensionMeter, transition, Welcome } from '@/components/experience';

type View='practice'|'progress'|'admin'|'settings';
const navigation=[{id:'practice',icon:LayoutGrid,name:'Арена'},{id:'progress',icon:TrendingUp,name:'Прогресс'},{id:'admin',icon:SlidersHorizontal,name:'Конструктор'},{id:'settings',icon:Settings2,name:'Настройки'}] as const;

export default function Home(){
 const {config,session,history,setConfig,start,clearSession}=useArena();
 const [view,setView]=useState<View>('practice');
 const [ready,setReady]=useState(false);
 const [welcome,setWelcome]=useState(true);
 const [quiet,setQuiet]=useState(false);
 const [brief,setBrief]=useState<Config|null>(null);
 const [review,setReview]=useState<Session|null>(null);
 useEffect(()=>{try{setWelcome(localStorage.getItem('arena-intro-v2')!=='done');setQuiet(localStorage.getItem('arena-quiet')==='true')}catch{}setReady(true)},[]);
 const completeWelcome=()=>{try{localStorage.setItem('arena-intro-v2','done')}catch{}setWelcome(false)};
 const toggleQuiet=()=>{setQuiet(value=>{try{localStorage.setItem('arena-quiet',String(!value))}catch{}return !value})};
 const active=ready?session:null;
 const past=ready?history:[];
 const pressure=active&&!active.ended&&view==='practice'?tension(active.config,active.turns):20;
 const total=past.reduce((sum,s)=>sum+outcome(s.config,s.turns).score,0);
 function preview(domain:Domain){setBrief(config.domain===domain?config:defaults[domain])}
 const screen=view==='practice'?(active?(active.ended?'result':'session'):'home'):view;
 return <MotionConfig transition={transition} reducedMotion={quiet?'always':'user'}><div className={quiet?'app-root quiet':'app-root'}>
 <AnimatePresence mode="wait">
 {!ready?<motion.div className="loading" key="loading" exit={{opacity:0}}><AudioLines size={35}/></motion.div>:welcome?<Arrival key="welcome"><Welcome onComplete={completeWelcome}/></Arrival>:<Arrival key="application" className="app-frame">
 <Atmosphere value={pressure} quiet={quiet}/>
 <aside className="sidebar"><button className="brand" aria-label="Главное меню" onClick={()=>setView('practice')}><span className="brand-mark"><AudioLines size={22}/></span><span>арена<span className="brand-dot">.</span></span></button><span className="sidebar-caption">ПРАКТИКА ДИАЛОГА</span><nav aria-label="Основная навигация">{navigation.map(item=><button key={item.id} aria-current={view===item.id?'page':undefined} onClick={()=>{setView(item.id);setReview(null)}} className={`nav-item ${view===item.id?'selected':''}`}>{view===item.id&&<motion.span className="nav-highlight" layoutId="navigation" transition={{type:'spring',stiffness:320,damping:36}}/>}<item.icon size={19}/><span>{item.name}</span>{item.id==='practice'&&active&&!active.ended&&<i className="live-dot"/>}</button>)}</nav><div className="sidebar-bottom"><button className="legend-link" onClick={()=>setWelcome(true)}><HelpCircle size={18}/><span>Как устроена арена</span></button><div className="profile"><div className="avatar">ВЫ</div><div><strong>Ваш следующий уровень</strong><small>{total%200} / 200 XP · Уровень {1+Math.floor(total/200)}</small><div className="mini-track"><i style={{width:`${total%200/2}%`}}/></div></div></div></div></aside>
 <main className="main"><header className="topbar"><div className="breadcrumb">Пространство практики <ChevronRight size={13}/><span>{navigation.find(n=>n.id===view)?.name}</span></div><div className="topbar-status"><span className="live-dot"/>Сценарный режим<button className="icon-button" aria-label="Повторить знакомство" onClick={()=>setWelcome(true)}><HelpCircle size={17}/></button></div></header>
 <div className="screen-host"><AnimatePresence mode="wait"><Arrival key={screen+(review?.id||'')} className={`screen screen-${screen}`}>
 {view==='practice'&&!active&&<Dashboard history={past} total={total} onPreview={preview} onConfigure={()=>setView('admin')}/>}
 {view==='practice'&&active&&!active.ended&&<Negotiation key={active.id} session={active} quiet={quiet}/>}
 {view==='practice'&&active?.ended&&<Results session={active} onRetry={()=>start(active.config)} onClose={clearSession}/>}
 {view==='progress'&&(review?<Results session={review} onRetry={()=>setBrief(review.config)} onClose={()=>setReview(null)}/>:<Progress history={past} onSelect={setReview} onPractice={()=>setView('practice')}/>)}
 {view==='admin'&&<Constructor config={config} onSave={setConfig} onPreview={c=>{setConfig(c);setBrief(c)}}/>}
 {view==='settings'&&<Settings quiet={quiet} onQuiet={toggleQuiet} onWelcome={()=>setWelcome(true)}/>}
 </Arrival></AnimatePresence></div>
 </main>
 </Arrival>}
 </AnimatePresence>
 <AnimatePresence>{brief&&!welcome&&<Modal title="Брифинг перед переговорами" onClose={()=>setBrief(null)}><div className="eyebrow">ПЕРЕД НАЧАЛОМ / БРИФИНГ</div><h2>{brief.topic}</h2><p className="brief-text">{scenarios[brief.domain].brief}</p><div className="brief-person"><div className="avatar">{scenarios[brief.domain].initials}</div><div><strong>{scenarios[brief.domain].person}</strong><small>{brief.role} · {brief.tone} тон</small></div></div><label>Сложность<select value={brief.difficulty} onChange={e=>setBrief({...brief,difficulty:e.target.value as Config['difficulty']})}>{['Базовый','Продвинутый','Эксперт'].map(x=><option key={x}>{x}</option>)}</select></label><p className="note">Цель собеседника: {brief.goal}. Для успеха — {threshold(brief)} очков и доверие от 40%.</p>{active&&!active.ended&&<p className="notice">Новая практика заменит текущую незавершённую сессию.</p>}<button className="button primary full" onClick={()=>{start(brief);setBrief(null);setView('practice');setReview(null)}}>Начать переговоры <ArrowRight size={17}/></button></Modal>}</AnimatePresence>
 </div></MotionConfig>;
}

function Dashboard({history,total,onPreview,onConfigure}:{history:Session[];total:number;onPreview:(d:Domain)=>void;onConfigure:()=>void}){
 return <div className="dashboard"><div className="heading"><div><span className="eyebrow">МЕСТО, ГДЕ РОЖДАЕТСЯ УВЕРЕННОСТЬ</span><h1>Любой разговор —<br/>новая возможность<span>.</span></h1><p>Не угадывайте правильный ответ. Найдите свой подход.</p></div><div className="dashboard-seal" aria-hidden="true"><AudioLines size={45} strokeWidth={1}/><span>ВЫ В АРЕНЕ</span></div></div>
 <div className="dashboard-stats"><span><Flag size={16}/><strong>{history.length}</strong> сессий</span><span><Zap size={16}/><strong>{total}</strong> опыта</span><span><Activity size={16}/> Ваши решения меняют диалог</span></div>
 <div className="section-label"><h2>С чего начнём?</h2><span>Два разговора. Много решений.</span></div>
 <div className="scenario-grid">{(['supplier','career'] as Domain[]).map((domain,i)=><motion.button whileHover={{y:-3}} whileTap={{scale:.995}} key={domain} className={`scenario-card ${domain}`} onClick={()=>onPreview(domain)}><div className="scenario-top"><span className="scenario-number">0{i+1}</span><span className="scenario-level">{defaults[domain].difficulty}</span></div><div className="scenario-symbol" aria-hidden="true">{i===0?<Target size={60} strokeWidth={.8}/>:<TrendingUp size={60} strokeWidth={.8}/>}</div><div className="scenario-copy"><span className="eyebrow">{scenarios[domain].label}</span><h3>{scenarios[domain].title}</h3><p>{scenarios[domain].description}</p></div><div className="scenario-bottom"><span><Clock3 size={13}/> 5–7 мин <i/> 4 этапа</span><strong>Начать <ArrowUpRight size={19}/></strong></div></motion.button>)}</div>
 <button className="custom-banner" onClick={onConfigure}><span><SlidersHorizontal size={20}/><strong>Ваш контекст. Ваши условия.</strong><small>Настройте собеседника и сложность.</small></span><ArrowRight size={19}/></button>
 <div className="dashboard-footer"><ShieldCheck size={13}/><span>Здесь можно ошибаться. Для этого мы и тренируемся.</span><Link href="/presentation">О проекте <ArrowUpRight size={13}/></Link></div>
 </div>;
}

function Negotiation({session:s,quiet}:{session:Session;quiet:boolean}){
 const {answer,finish,setReplyDraft}=useArena();const text=s.draft||'';const setText=setReplyDraft;const [busy,setBusy]=useState(false);const busyRef=useRef(false);const timer=useRef<ReturnType<typeof setTimeout>|null>(null);
 const [now,setNow]=useState(Date.now());const [showMission,setShowMission]=useState(false);const log=useRef<HTMLDivElement>(null);const reduced=useReducedMotion();
 useEffect(()=>{const t=setInterval(()=>setNow(Date.now()),1000);return()=>{clearInterval(t);if(timer.current)clearTimeout(timer.current)}},[]);
 useEffect(()=>{const el=log.current;if(el)el.scrollTo({top:el.scrollHeight,behavior:reduced||quiet?'instant':'smooth'})},[s.turns.length,reduced,quiet]);
 const pressure=tension(s.config,s.turns);const previous=s.turns.length?tension(s.config,s.turns.slice(0,-1)):undefined;const mood=tensionState(pressure);const result=outcome(s.config,s.turns);const stage=s.turns.length;
 function choose(c:Choice){if(busyRef.current||stage>=4)return;busyRef.current=true;setBusy(true);answer(c);setText('');timer.current=setTimeout(()=>{busyRef.current=false;setBusy(false)},quiet||reduced?180:750)}
 function send(){if(text.trim().length>=5)choose(evaluateText(text.trim(),s.config.domain,stage))}
 return <div className={`negotiation tension-${mood.level}`} data-tension={pressure}><div className="session-heading"><div><span className="eyebrow">ВСТРЕЧА В АРЕНЕ · {stage}/4 ЭТАПА</span><h1>{s.config.topic}</h1></div><div className="session-controls"><span className="timer"><Clock3 size={14}/>{formatTime(now-s.started)}</span><button className="icon-button" aria-label="Показать задачу" onClick={()=>setShowMission(true)}><Target size={18}/></button></div></div>
 <div className="session-layout"><section className="conversation"><div className="opponent"><div className={`avatar mood-avatar ${mood.level}`}>{scenarios[s.config.domain].initials}<span/></div><div><strong>{scenarios[s.config.domain].person}</strong><small>{s.config.role}</small></div><span className={`mood-chip ${mood.level}`}>{mood.label}</span></div><div className="mobile-tension"><TensionMeter value={pressure} previous={previous} compact/></div>
 <div className="messages" ref={log} role="log" aria-label="История переговоров" aria-live="polite"><div className="dialog-intro"><span>Переговоры начались</span></div><div className="message theirs"><small>{scenarios[s.config.domain].person.split(' ')[0]}</small>{scenarios[s.config.domain].opening}</div>{s.turns.map((turn,i)=><div key={i} className="exchange"><div className="stage-divider">{stages[i]}</div><motion.div className="message yours" initial={{opacity:0,y:reduced?0:8}} animate={{opacity:1,y:0}} transition={transition}>{turn.text}</motion.div><motion.div className="message theirs" initial={{opacity:0,y:reduced?0:8}} animate={{opacity:1,y:0}} transition={{...transition,delay:quiet||reduced?0:.2}}><small>{scenarios[s.config.domain].person.split(' ')[0]}</small>{turn.reply}</motion.div><div className="turn-feedback"><Sparkles size={12}/>{turn.skill} · +{turn.points} XP</div></div>)}</div>
 <div className="composer"><AnimatePresence mode="wait">{stage<4?<Arrival key={stage} className="response-block"><div className="composer-heading"><span>ВАШ ХОД</span><strong>{stages[stage]}</strong><span>{stage+1}/4</span></div><div className="options">{choices(s.config.domain,stage).map((c,i)=><button disabled={busy} key={c.text} onClick={()=>choose(c)}><span className="option-number">{i+1}</span><span>{c.text}</span><ArrowUpRight size={15}/></button>)}</div><form className="input-row" onSubmit={e=>{e.preventDefault();send()}}><input aria-label="Ваша реплика" placeholder="Или ответьте своими словами…" value={text} maxLength={800} disabled={busy} onChange={e=>setText(e.target.value)}/><button className="send-button" aria-label="Отправить реплику" disabled={busy||text.trim().length<5}><Send size={17}/></button></form><div className="input-note">{busy?'Собеседник обдумывает ваш ответ…':'От 5 символов · Enter — отправить · Оценка по признакам приёма'}</div></Arrival>:<Arrival key="finish" className="finish-prompt"><div><Check size={18}/><span>Все четыре этапа пройдены. Посмотрим, что получилось?</span></div><button disabled={busy} className="button primary" onClick={finish}>Посмотреть разбор <ArrowRight size={16}/></button></Arrival>}</AnimatePresence></div>
 </section><aside className="session-sidebar"><TensionMeter value={pressure} previous={previous}/><div className="session-mission"><span className="eyebrow"><Target size={13}/> ВАША ЗАДАЧА</span><p>{scenarios[s.config.domain].brief}</p></div><div className="session-stage-list">{stages.map((label,i)=><div key={label} className={i<=stage?'reached':''}><span>{stage>i?<Check size={12}/>:i+1}</span>{label}</div>)}</div><div className="trust-panel"><div><span>Доверие</span><strong>{result.trust}%</strong></div><div className="mini-track"><motion.i animate={{width:result.trust+'%'}} transition={{duration:.8}}/></div><small>Цель: {threshold(s.config)} очков и доверие от 40%</small></div><button className="text-button leave-button" onClick={finish}>Завершить досрочно <ArrowUpRight size={14}/></button></aside></div>
 <button className="mobile-leave" onClick={finish}>Завершить и разобрать <ArrowUpRight size={12}/></button>
 <AnimatePresence>{showMission&&<Modal title="Ваша задача" onClose={()=>setShowMission(false)}><span className="eyebrow">ВАША ЗАДАЧА</span><h2>{s.config.topic}</h2><p className="brief-text">{scenarios[s.config.domain].brief}</p><TensionMeter value={pressure}/><p className="note">Для успеха: {threshold(s.config)} очков, доверие не ниже 40%, четыре этапа.</p><button className="button primary full" onClick={()=>setShowMission(false)}>Вернуться к разговору <ArrowRight size={16}/></button></Modal>}</AnimatePresence>
 </div>;
}

function Results({session:s,onRetry,onClose}:{session:Session;onRetry:()=>void;onClose:()=>void}){
 const [step,setStep]=useState(0);const result=outcome(s.config,s.turns);const turn=s.turns[step];
 return <div className="results"><div className="heading compact-heading"><div><span className="eyebrow">РАЗБОР ПЕРЕГОВОРОВ</span><h1>{result.won?'Общий язык найден.':s.turns.length<4?'Практика остановлена.':'Каждая попытка делает вас сильнее.'}</h1><p>{result.won?'Вы приблизили обе стороны к общей цели.':'Разберём решения и найдём более сильный следующий ход.'}</p></div><Trophy className="result-trophy" size={38} strokeWidth={1}/></div><div className="result-metrics"><Metric value={`${result.score}/100`} label="Результат"/><Metric value={`${result.trust}%`} label="Доверие"/><Metric value={`${tension(s.config,s.turns)}%`} label="Напряжённость"/><Metric value={formatTime((s.ended||Date.now())-s.started)} label="Время"/></div>
 <section className="review-panel"><div className="review-tabs" aria-label="Этапы разбора">{s.turns.map((_,i)=><button key={i} aria-pressed={step===i} className={step===i?'active':''} onClick={()=>setStep(i)}><span>{i+1}</span><span>{stages[i]}</span></button>)}</div><div className="review-content scroll-region"><AnimatePresence mode="wait"><Arrival key={step}>{turn?<><div className="review-label"><span>ВАША РЕПЛИКА</span><strong>+{turn.points} XP</strong></div><blockquote>«{turn.text}»</blockquote><div className="feedback-box"><Sparkles size={18}/><p>{turn.feedback}</p></div>{turn.points<19?<div className="better"><span>ПОПРОБУЙТЕ ТАК</span><p>{choices(s.config.domain,step)[0].text}</p></div>:<div className="better"><span>СОХРАНИТЕ ЭТОТ ПРИЁМ</span><p>{turn.skill}: попробуйте применить его в другом сценарии или сформулировать своими словами.</p></div>}</>:<div className="empty-state"><Compass size={30}/><h2>Разговор ещё не начался</h2><p>Сделайте первый ход, чтобы получить обратную связь.</p></div>}</Arrival></AnimatePresence></div></section><div className="result-footer"><button className="button secondary" onClick={onClose}><ArrowLeft size={16}/> К списку</button><span>{s.config.difficulty} · {s.turns.length}/4 этапа</span><button className="button primary" onClick={onRetry}><RotateCcw size={16}/> Попробовать иначе</button></div></div>;
}
function Metric({value,label}:{value:string;label:string}){return <div className="metric"><strong>{value}</strong><span>{label}</span></div>}
function Progress({history,onSelect,onPractice}:{history:Session[];onSelect:(s:Session)=>void;onPractice:()=>void}){
 return <div className="progress-screen"><div className="heading compact-heading"><div><span className="eyebrow">КАЖДАЯ ПОПЫТКА ИМЕЕТ ЗНАЧЕНИЕ</span><h1>Ваш путь переговорщика<span>.</span></h1><p>Вернитесь к любому разговору и посмотрите на него по-новому.</p></div></div><div className="result-metrics"><Metric value={String(history.length)} label="Сессий"/><Metric value={String(history.filter(s=>outcome(s.config,s.turns).won).length)} label="Договорённостей"/><Metric value={String(history.reduce((a,s)=>a+outcome(s.config,s.turns).score,0))} label="Очков опыта"/></div><div className="history-list scroll-region">{history.length?history.map(s=><button className="history-item" key={s.id} onClick={()=>onSelect(s)}><div className="history-icon">{outcome(s.config,s.turns).won?<Check size={19}/>:<Flag size={19}/>}</div><div><strong>{s.config.topic}</strong><small>{new Date(s.started).toLocaleDateString('ru-RU')} · {s.config.difficulty} · {s.turns.length}/4 этапа</small></div><span>{outcome(s.config,s.turns).score}<small>/100</small></span><ArrowUpRight size={18}/></button>):<div className="empty-state"><Compass size={38}/><h2>Первый разговор — начало пути</h2><p>Пройдите сценарий. Здесь появятся результаты и разбор.</p><button className="button primary" onClick={onPractice}>Выбрать разговор <ArrowRight size={16}/></button></div>}</div><p className="storage-note"><ShieldCheck size={13}/> Последние 50 сессий сохраняются в этом браузере.</p></div>;
}

function Constructor({config,onSave,onPreview}:{config:Config;onSave:(c:Config)=>void;onPreview:(c:Config)=>void}){
 const [draft,setDraft]=useState(config);const [saved,setSaved]=useState(false);
 function update<K extends keyof Config>(key:K,value:Config[K]){setDraft({...draft,[key]:value});setSaved(false)}
 const valid=draft.topic.trim()&&draft.role.trim()&&draft.goal.trim();
 return <div className="constructor"><div className="heading compact-heading"><div><span className="eyebrow">КОНСТРУКТОР КОНТЕКСТА</span><h1>Задайте условия разговора<span>.</span></h1><p>Каждая настройка — новый повод попробовать другую стратегию.</p></div></div><form className="constructor-form" onSubmit={e=>{e.preventDefault();if(valid){onSave(draft);setSaved(true)}}}><div className="form-body scroll-region"><div className="form-grid"><label>Сфера<select value={draft.domain} onChange={e=>{setDraft({...defaults[e.target.value as Domain],difficulty:draft.difficulty,tone:draft.tone});setSaved(false)}}><option value="supplier">Закупки и продажи</option><option value="career">Карьера и развитие</option></select></label><label>Тема переговоров<input required maxLength={100} value={draft.topic} onChange={e=>update('topic',e.target.value)}/></label><label>Сложность<select value={draft.difficulty} onChange={e=>update('difficulty',e.target.value as Config['difficulty'])}>{['Базовый','Продвинутый','Эксперт'].map(x=><option key={x}>{x}</option>)}</select></label><label>Тон собеседника<select value={draft.tone} onChange={e=>update('tone',e.target.value as Config['tone'])}>{['Дружелюбный','Сдержанный','Жёсткий'].map(x=><option key={x}>{x}</option>)}</select></label><label>Роль собеседника<input required maxLength={80} value={draft.role} onChange={e=>update('role',e.target.value)}/></label><label>Его цель<input required maxLength={180} value={draft.goal} onChange={e=>update('goal',e.target.value)}/></label></div><div className="context-preview"><div><span className="eyebrow">АТМОСФЕРА НА СТАРТЕ</span><TensionMeter value={tension(draft,[])} compact/></div><p>Тон и сложность задают начальное напряжение. Сфера выбирает сюжет, цель и тон меняют ответы. Тема и роль уточняют контекст.</p></div><p className="note">Конструктор использует два подготовленных сюжета. Произвольная тема не создаёт новый сценарий.</p></div><div className="form-footer"><button className="button secondary" disabled={!valid} type="submit"><Check size={16}/>{saved?'Сохранено':'Сохранить'}</button><span role="status">{saved?'Контекст готов к практике':''}</span><button className="button primary" disabled={!valid} type="button" onClick={()=>onPreview(draft)}>Протестировать <Play size={15}/></button></div></form></div>;
}

function Settings({quiet,onQuiet,onWelcome}:{quiet:boolean;onQuiet:()=>void;onWelcome:()=>void}){
 return <div className="settings-screen"><div className="heading compact-heading"><div><span className="eyebrow">ВАШ КОМФОРТ — ВАШИ ПРАВИЛА</span><h1>Настройки арены<span>.</span></h1><p>Выберите ритм, в котором вам удобно практиковаться.</p></div></div><div className="settings-body scroll-region"><section className="setting-card"><span className="setting-icon"><Activity size={22}/></span><div><h2>Спокойный режим</h2><p>Убирает движение фона и пульсацию. Напряжённость остаётся видна в цифрах и цвете.</p></div><button role="switch" aria-label="Спокойный режим" aria-checked={quiet} onClick={onQuiet} className={`toggle ${quiet?'on':''}`}><span/></button></section><section className="setting-card"><span className="setting-icon"><Compass size={22}/></span><div><h2>Легенда и знакомство</h2><p>История арены и короткая экскурсия по кнопкам, репликам и показателям.</p></div><button className="button secondary" onClick={onWelcome}>Посмотреть <ArrowUpRight size={16}/></button></section><section className="setting-card api-card"><span className="setting-icon"><KeyRound size={22}/></span><div><div className="api-title"><h2>Нейросеть · OpenAI</h2><span className="status-tag">Не подключена</span></div><p>Получите API-ключ в кабинете OpenAI. Сейчас арена работает на сценарном движке; создание ключа само по себе не подключает модель.</p><div className="api-links"><a className="button primary" href="https://platform.openai.com/api-keys" target="_blank" rel="noopener noreferrer">Получить API-ключ <ArrowUpRight size={16}/></a><a className="text-button" href="https://developers.openai.com/api/docs/quickstart" target="_blank" rel="noopener noreferrer">Инструкция OpenAI <ArrowUpRight size={14}/></a></div></div></section><div className="settings-footnote"><ShieldCheck size={15}/><p>Настройки и результаты хранятся в этом браузере. Системное ограничение анимаций также учитывается.</p></div></div></div>;
}
function formatTime(ms:number){const seconds=Math.max(0,Math.floor(ms/1000));return `${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`}
